// Colors sourced from build/js/tokens.js, generated by Style Dictionary
// (`npm run tokens:build`) from tokens/primitives.json, which extract-tokens.mjs
// generates by regex-scanning raw hex literals out of assets/css/unikwan.css — the
// indices carry no semantic meaning, only "Nth hex first seen in the CSS". extract-tokens.mjs
// merges onto the existing file (stable, append-only) rather than regenerating from
// scratch, so these indices no longer shift/disappear on a re-run — but if primitives.json
// is ever hand-edited or regenerated by a different tool, re-verify against the hex values
// in the comments below rather than assuming the index still matches.
import {
  GlobalColorColorExtracted60 as background, // matches .mobile_navbar_container background, unikwan.css — hex #231642
  GlobalColorColorExtracted16 as text, // matches .color_white, unikwan.css — hex #ffffff
  GlobalColorColorExtracted74 as textMuted, // matches .mobile_submenu color, unikwan.css — hex #e5e5e5
  GlobalColorColorExtracted146 as accent, // matches .header_vertical_border, unikwan.css — hex #ca51d1
  GlobalColorColorExtracted65 as cta, // matches .button_blue background & .mobile_active_dot, unikwan.css — hex #2d6ee0
} from "../../build/js/tokens.js";

export const navTokens = {
  background,
  backgroundTranslucent: "rgba(35, 22, 66, 0.71)", // alpha variant of `background`, per .mobile_navbar_container

  text,
  textMuted,
  accent,
  cta,

  // rgba(255,255,255,x) states from .nav_name:hover / .nav_name.active / .home_icon_container
  // — alpha variants of `text`, not separate swatches in primitives.json
  hoverBorder: "rgba(255, 255, 255, 0.33)",
  activeBg: "rgba(255, 255, 255, 0.1)",
  hairline: "rgba(255, 255, 255, 0.1)",
  hairlineFaint: "rgba(255, 255, 255, 0.05)",
};
