// Colors sourced from build/js/tokens.js, generated by Style Dictionary
// (`npx style-dictionary build`, config.json) from tokens/primitives.json.
// primitives.json only has 144 generic "color-extracted-N" swatches — no semantic
// names, no Figma variable metadata reachable (Variables API needs an Enterprise
// scope this project doesn't have, and no styles/components were reachable via
// the Desktop Bridge). So each import below is picked by index, cross-checked
// against the live nav styling in assets/css/unikwan.css for an exact hex match —
// not a blind guess across all 144. Re-run the build after editing primitives.json.
import {
  GlobalColorColorExtracted60 as background, // matches .mobile_navbar_container background, unikwan.css:8245
  GlobalColorColorExtracted2 as text, // matches .color_white, unikwan.css:209
  GlobalColorColorExtracted73 as textMuted, // matches .mobile_submenu color, unikwan.css:8402
  GlobalColorColorExtracted28 as accent, // matches .header_vertical_border, unikwan.css:510
  GlobalColorColorExtracted14 as cta, // matches .button_blue background & .mobile_active_dot, unikwan.css:304,8382
} from "../../build/js/tokens.js";

export const navTokens = {
  background,
  backgroundTranslucent: "rgba(35, 22, 66, 0.71)", // alpha variant of `background`, per .mobile_navbar_container

  text,
  textMuted,
  accent,
  cta,

  // rgba(255,255,255,x) states from .nav_name:hover / .nav_name.active / .home_icon_container
  // — alpha variants of `text`, not separate swatches in primitives.json
  hoverBorder: "rgba(255, 255, 255, 0.33)",
  activeBg: "rgba(255, 255, 255, 0.1)",
  hairline: "rgba(255, 255, 255, 0.1)",
  hairlineFaint: "rgba(255, 255, 255, 0.05)",
};
